'use client'

import Head from "next/head";
import { useUsername } from "./_app";
import { useRouter } from "next/navigation";

export default function Home() {
  const { username, setUsername } = useUsername();
  const router = useRouter();

  function changeUsername(e: { preventDefault: () => void }) {
    e.preventDefault();
    const inputUsername: HTMLInputElement | null =
      document.querySelector("#userNameBox");

    if (inputUsername) {
      setUsername(inputUsername.value.trim());
      router.push("/chat");
    }
  }

  return (
    <>
      <Head>
        <title>Live Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        id="map"
        className="flex items-center justify-center w-screen h-screen bg-zinc-800"
      >
        <form action="" onSubmit={changeUsername}>
          <input
            id="userNameBox"
            type="text"
            placeholder="Choose your username"
            className="p-4 text-white shadow-sm bg-zinc-700/70 ring-1 ring-inset ring-zinc-800/60 rounded-xl focus:border-none highlight-white"
            autoComplete="off"
          />
          <button
            type="submit"
            className="p-4 ml-4 text-white transition-colors shadow-sm rounded-xl bg-zinc-700/70 highlight-white hover:bg-zinc-700/50"
          >
            Go
          </button>
        </form>
      </main>
    </>
  );
}
